name: CI

run-name: "CI • ${{ github.ref_name }}"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DJANGO_ENV: dev
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DEBUG: "False"
      ALLOWED_HOSTS: "localhost,127.0.0.1"

      DATABASE_NAME: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: localhost
      DATABASE_PORT: "5432"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.1

      - name: Set up uv
        uses: astral-sh/setup-uv@v10.1.0
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: uv sync --locked --dev

      - name: Django checks
        run: uv run python manage.py check

      - name: Check migrations
        run: uv run python manage.py makemigrations --check --dry-run

      - name: Run tests
        env:
          DJANGO_ENV: test
        run: uv run python manage.py test
