name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.1

      - name: Set up uv
        uses: astral-sh/setup-uv@v10.0.1
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: uv sync --locked --dev

      - name: Lint
        run: uv run ruff check --output-format=github .

      - name: Check formatting
        run: uv run ruff format --check .

      - name: Type check
        run: uv run mypy

      - name: Django checks
        run: uv run python manage.py check

      - name: Run tests
        run: uv run python manage.py test